repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
              frontend/src/client/.*|
              frontend/src/routeTree.gen.ts
          )$
      - id: trailing-whitespace
        exclude: |
          (?x)^(
              frontend/src/client/.*|
              frontend/src/routeTree.gen.ts
          )$
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: mixed-line-ending

  # Backend formatting and linting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.4
    hooks:
      - id: ruff-check
        args:
          - --fix
        files: ^backend/.*\.py$
      - id: ruff-format
        files: ^backend/.*\.py$

  # Frontend formatting and linting
  - repo: local
    hooks:
      - id: local-biome-check
        name: biome check
        entry: bash -c 'cd frontend && pnpm check:fix'
        language: system
        types:
          - text
        files: "\\.(jsx?|tsx?|c(js|ts)|m(js|ts)|d\\.(ts|cts|mts)|jsonc?|css|svelte|vue|astro|graphql|gql)$"
