[project]
name = "backend"
version = "0.1.0"
description = "Container Use UI API"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
]
