// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetApiV1EnvironmentsData, GetApiV1EnvironmentsResponse, GetApiV1FilesData, GetApiV1FilesResponse } from './types.gen';

export class DefaultService {
    /**
     * @param data The data for the request.
     * @param data.folder Working directory for the CLI command
     * @param data.cli Path to the container-use CLI
     * @returns EnvironmentList List of environments
     * @throws ApiError
     */
    public static getApiV1Environments(data: GetApiV1EnvironmentsData = {}): CancelablePromise<GetApiV1EnvironmentsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/environments',
            query: {
                folder: data.folder,
                cli: data.cli
            },
            errors: {
                500: 'Internal server error'
            }
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.path Directory path to list. Defaults to home directory if not provided
     * @returns unknown Directory listing
     * @throws ApiError
     */
    public static getApiV1Files(data: GetApiV1FilesData = {}): CancelablePromise<GetApiV1FilesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/files',
            query: {
                path: data.path
            },
            errors: {
                500: 'Internal server error'
            }
        });
    }
    
}