// This file is auto-generated by @hey-api/openapi-ts

export type Environment = {
    id: string;
    title: string;
    created: string;
    updated: string;
};

export type EnvironmentList = Array<Environment>;

export type Error = {
    error: string;
    details?: {
        exitCode: number;
        stderr: string;
        command: string;
        cwd: string;
    };
};

export type GetApiV1EnvironmentsData = {
    /**
     * Path to the container-use CLI
     */
    cli?: string;
    /**
     * Working directory for the CLI command
     */
    folder?: string;
};

export type GetApiV1EnvironmentsResponse = (EnvironmentList);