// This file is auto-generated by @hey-api/openapi-ts

export type Environment = {
    id: string;
    title: string;
    created: string;
    updated: string;
};

export type EnvironmentDiff = {
    environmentId: string;
    diff: string;
    timestamp: string;
};

export type EnvironmentList = Array<Environment>;

export type EnvironmentLogs = {
    environmentId: string;
    logs: string;
    timestamp: string;
};

export type Error = {
    error: string;
    details?: {
        exitCode: number;
        stderr: string;
        command: string;
        cwd: string;
    };
};

export type GetApiV1EnvironmentsData = {
    /**
     * Path to the container-use CLI
     */
    cli?: string;
    /**
     * Working directory for the CLI command
     */
    folder?: string;
};

export type GetApiV1EnvironmentsResponse = (EnvironmentList);

export type GetApiV1EnvironmentsByIdLogsData = {
    /**
     * Path to the container-use CLI
     */
    cli?: string;
    /**
     * Working directory for the CLI command
     */
    folder?: string;
    /**
     * Environment ID
     */
    id: string;
};

export type GetApiV1EnvironmentsByIdLogsResponse = (EnvironmentLogs);

export type GetApiV1EnvironmentsByIdDiffData = {
    /**
     * Path to the container-use CLI
     */
    cli?: string;
    /**
     * Working directory for the CLI command
     */
    folder?: string;
    /**
     * Environment ID
     */
    id: string;
};

export type GetApiV1EnvironmentsByIdDiffResponse = (EnvironmentDiff);

export type GetApiV1FilesData = {
    /**
     * Directory path to list. Defaults to home directory if not provided
     */
    path?: string;
};

export type GetApiV1FilesResponse = ({
    /**
     * Current directory path
     */
    path: string;
    /**
     * List of files and directories in the current path
     */
    items: Array<{
        /**
         * Name of the file or directory
         */
        name: string;
        /**
         * Full path to the file or directory
         */
        path: string;
        /**
         * Type of the entry
         */
        type: 'file' | 'directory';
        /**
         * Size of the file in bytes (only for files)
         */
        size?: number;
        /**
         * Last modified timestamp
         */
        modified?: string;
    }>;
    /**
     * Parent directory path, null if at root
     */
    parent: (string) | null;
});