name: Publish Package

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 10

      - name: Setup Node 20
        uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm compile

      - name: Run all tests
        run: pnpm test

      - name: Publish
        # Use `--no-git-checks` due to how GitHub Actions checks out
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_ELEVATED }}
